//! Pattern mapping/demapping and symbol reset - original/source/PatternCoding.c

use crate::error::{BpeError, BpeResult};
use crate::types::SymbolDetails;

const BIT2_PATTERN: [u8; 4] = [0, 2, 1, 3];
const BIT3_PATTERN: [u8; 8] = [1, 4, 0, 5, 2, 6, 3, 7];
const BIT3_PATTERN_TRAN_D: [u8; 8] = [0, 3, 0, 4, 1, 5, 2, 6];
const BIT4_PATTERN_TYPE_CI: [u8; 16] = [10, 1, 3, 6, 2, 5, 9, 12, 0, 8, 7, 13, 4, 14, 11, 15];
const BIT4_PATTERN_TYPE_HIJ_TRAN_HI: [u8; 16] =
    [0, 1, 3, 6, 2, 5, 9, 11, 0, 8, 7, 12, 4, 13, 10, 14];

const ENUM_TRAN_D: u8 = crate::types::ENUM_TRAN_D;
const ENUM_TYPE_CI: u8 = crate::types::ENUM_TYPE_CI;
const ENUM_TRAN_HI: u8 = crate::types::ENUM_TRAN_HI;
const ENUM_TYPE_HIJ: u8 = crate::types::ENUM_TYPE_HIJ;

pub fn pattern_mapping(sym: &mut SymbolDetails) -> BpeResult<()> {
    match sym.sym_len {
        0 => Ok(()),
        1 => {
            sym.sym_mapped_pattern = sym.sym_val;
            Ok(())
        }
        2 => {
            sym.sym_mapped_pattern = BIT2_PATTERN[sym.sym_val as usize];
            Ok(())
        }
        3 => {
            if sym.type_ == ENUM_TRAN_D {
                sym.sym_mapped_pattern = BIT3_PATTERN_TRAN_D[sym.sym_val as usize];
            } else {
                sym.sym_mapped_pattern = BIT3_PATTERN[sym.sym_val as usize];
            }
            Ok(())
        }
        4 => {
            if sym.type_ == ENUM_TYPE_CI {
                sym.sym_mapped_pattern = BIT4_PATTERN_TYPE_CI[sym.sym_val as usize];
            } else if sym.type_ == ENUM_TRAN_HI || sym.type_ == ENUM_TYPE_HIJ {
                sym.sym_mapped_pattern = BIT4_PATTERN_TYPE_HIJ_TRAN_HI[sym.sym_val as usize];
            }
            Ok(())
        }
        _ => Err(BpeError::PatternCodingError),
    }
}

pub fn de_mapping_pattern(sym: &mut SymbolDetails) -> BpeResult<()> {
    match sym.sym_len {
        1 => {
            sym.sym_val = sym.sym_mapped_pattern;
            Ok(())
        }
        2 => {
            for i in 0..4u8 {
                if sym.sym_mapped_pattern == BIT2_PATTERN[i as usize] {
                    sym.sym_val = i;
                    break;
                }
            }
            Ok(())
        }
        3 => {
            if sym.type_ == ENUM_TRAN_D {
                for i in 1..8u8 {
                    if sym.sym_mapped_pattern == BIT3_PATTERN_TRAN_D[i as usize] {
                        sym.sym_val = i;
                        break;
                    }
                }
            } else {
                for i in 0..8u8 {
                    if sym.sym_mapped_pattern == BIT3_PATTERN[i as usize] {
                        sym.sym_val = i;
                        break;
                    }
                }
            }
            Ok(())
        }
        4 => {
            if sym.type_ == ENUM_TYPE_CI {
                for i in 0..16u8 {
                    if sym.sym_mapped_pattern == BIT4_PATTERN_TYPE_CI[i as usize] {
                        sym.sym_val = i;
                        break;
                    }
                }
            } else if sym.type_ == ENUM_TRAN_HI || sym.type_ == ENUM_TYPE_HIJ {
                for i in 1..16u8 {
                    if sym.sym_mapped_pattern == BIT4_PATTERN_TYPE_HIJ_TRAN_HI[i as usize] {
                        sym.sym_val = i;
                        break;
                    }
                }
            }
            Ok(())
        }
        _ => Err(BpeError::PatternCodingError),
    }
}

pub fn bit_plane_symbol_reset(sym: &mut SymbolDetails) {
    sym.sign = 0;
    sym.sym_len = 0;
    sym.sym_mapped_pattern = 0;
    sym.sym_val = 0;
    sym.type_ = 0;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{ENUM_TRAN_B, ENUM_TYPE_P};
    use std::fs;
    use std::path::PathBuf;

    /// Cross-checks against verify/vectors/pattern_vectors.txt, generated by
    /// verify/c_unit_tests/gen_pattern_vectors.c from the real C reference.
    /// Each line is `sym_len type num_values mapped_csv`: mapping sym_val =
    /// 0..num_values with this module's pattern_mapping must produce the
    /// exact same mapped codes the C PatternMapping produced.
    ///
    /// Ignored by default (like golden_roundtrip.rs) because it needs
    /// verify/run_unit_vectors.py to have generated the vectors file first;
    /// that script runs this test with `--include-ignored`.
    #[test]
    #[ignore]
    fn shared_vectors_match_c_reference() {
        let vectors_path =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../verify/vectors/pattern_vectors.txt");
        let text = fs::read_to_string(&vectors_path).unwrap_or_else(|e| {
            panic!(
                "couldn't read {}: {e} (run verify/run_unit_vectors.py first)",
                vectors_path.display()
            )
        });

        let mut checked = 0;
        for line in text.lines() {
            let fields: Vec<&str> = line.split_whitespace().collect();
            let [sym_len, type_, num_values, mapped_csv] = fields[..] else {
                panic!("malformed vector line: {line}");
            };
            let sym_len: u8 = sym_len.parse().unwrap();
            let type_: u8 = type_.parse().unwrap();
            let num_values: u32 = num_values.parse().unwrap();
            let expected: Vec<u8> = mapped_csv.split(',').map(|s| s.parse().unwrap()).collect();
            assert_eq!(expected.len() as u32, num_values);

            for sym_val in 0..num_values {
                let mut sym = SymbolDetails {
                    sym_val: sym_val as u8,
                    sym_len,
                    type_,
                    ..Default::default()
                };
                pattern_mapping(&mut sym).unwrap();
                assert_eq!(
                    sym.sym_mapped_pattern, expected[sym_val as usize],
                    "sym_len={} type={} sym_val={}: rust produced {} but C reference produced {}",
                    sym_len, type_, sym_val, sym.sym_mapped_pattern, expected[sym_val as usize]
                );
            }
            checked += 1;
        }
        assert!(checked > 0, "vectors file was empty");
    }

    fn roundtrip(sym_len: u8, type_: u8, sym_val: u8) -> u8 {
        let mut sym = SymbolDetails {
            sym_val,
            sym_len,
            type_,
            ..Default::default()
        };
        pattern_mapping(&mut sym).unwrap();
        let mapped = sym.sym_mapped_pattern;
        let mut back = SymbolDetails {
            sym_mapped_pattern: mapped,
            sym_len,
            type_,
            ..Default::default()
        };
        de_mapping_pattern(&mut back).unwrap();
        back.sym_val
    }

    #[test]
    fn one_bit_symbols_pass_through() {
        for value in 0..=1u8 {
            assert_eq!(roundtrip(1, ENUM_TYPE_P, value), value);
        }
    }

    #[test]
    fn two_bit_symbols_are_bijective() {
        for value in 0..4u8 {
            assert_eq!(roundtrip(2, ENUM_TYPE_P, value), value);
        }
    }

    #[test]
    fn three_bit_symbols_are_bijective() {
        for value in 0..8u8 {
            assert_eq!(roundtrip(3, ENUM_TRAN_B, value), value);
        }
    }

    /// The TranD table repeats pattern 0 at index 0 and 2, so the C decoder
    /// starts its search at 1 and symbol value 0 is never emitted.
    #[test]
    fn three_bit_tran_d_symbols_are_bijective_from_one() {
        for value in 1..8u8 {
            assert_eq!(roundtrip(3, ENUM_TRAN_D, value), value);
        }
    }

    #[test]
    fn four_bit_type_ci_symbols_are_bijective() {
        for value in 0..16u8 {
            assert_eq!(roundtrip(4, ENUM_TYPE_CI, value), value);
        }
    }

    /// Same repeated-pattern situation as TranD: value 0 is unused.
    #[test]
    fn four_bit_tran_hi_and_type_hij_symbols_are_bijective_from_one() {
        for value in 1..16u8 {
            assert_eq!(roundtrip(4, ENUM_TRAN_HI, value), value);
            assert_eq!(roundtrip(4, ENUM_TYPE_HIJ, value), value);
        }
    }

    #[test]
    fn zero_length_symbol_is_ignored() {
        let mut sym = SymbolDetails {
            sym_val: 3,
            sym_len: 0,
            ..Default::default()
        };
        pattern_mapping(&mut sym).unwrap();
        assert_eq!(sym.sym_mapped_pattern, 0);
    }

    #[test]
    fn too_long_symbol_is_rejected() {
        let mut sym = SymbolDetails {
            sym_len: 5,
            ..Default::default()
        };
        assert!(pattern_mapping(&mut sym).is_err());
        assert!(de_mapping_pattern(&mut sym).is_err());
    }

    #[test]
    fn reset_clears_every_field() {
        let mut sym = SymbolDetails {
            sym_val: 1,
            sym_len: 2,
            sym_mapped_pattern: 3,
            sign: 1,
            type_: ENUM_TYPE_CI,
        };
        bit_plane_symbol_reset(&mut sym);
        assert_eq!(sym.sym_val, 0);
        assert_eq!(sym.sym_len, 0);
        assert_eq!(sym.sym_mapped_pattern, 0);
        assert_eq!(sym.sign, 0);
        assert_eq!(sym.type_, 0);
    }
}
