//! Gaggle Rice parameter `k` selection (DC / AC depth).

/// Sentinel k value meaning "emit uncoded words for this gaggle".
pub(crate) const UNCODED_FLAG: i32 = 0xFF;

// Heuristic thresholds matching the original C DC/AC gaggle k selection.
const HEUR_UNCODED_DELTA_MUL: i64 = 64;
const HEUR_UNCODED_J_MUL: i64 = 23;
const HEUR_K0_J_MUL: i64 = 207;
const HEUR_K0_DELTA_MUL: i64 = 128;
const HEUR_LARGE_K_SHIFT: i64 = 5;
const HEUR_LARGE_K_DELTA_MUL: i64 = 128;
const HEUR_LARGE_K_J_MUL: i64 = 49;
const HEUR_SCAN_SHIFT_BASE: i64 = 7;
const HEUR_SCAN_DELTA_MUL: i64 = 128;
const HEUR_SCAN_J_MUL: i64 = 49;

/// Choose Rice parameter `k` for one gaggle of mapped magnitudes.
///
/// `mapped[i]` is the mapped DC or AC value for block `start_index + i` style
/// absolute indices via the slice covering `[start_index, start_index+gaggles)`.
/// `opt_select` mirrors `header.part3.opt_dc_select` (exhaustive search vs heuristic).
pub(crate) fn select_rice_k(
    mapped: &[u32],
    start_index: usize,
    gaggles: usize,
    n: u8,
    max_k: i32,
    opt_select: bool,
) -> i32 {
    if opt_select {
        let mut min_k = UNCODED_FLAG;
        let mut min_bits: u32 = 0xFFFF;
        for k in 0..=max_k {
            let mut total_bits: u32 = if start_index == 0 { n as u32 } else { 0 };
            for i in start_index.max(1)..(start_index + gaggles) {
                total_bits += ((mapped[i] >> k) + 1) + k as u32;
            }
            if (total_bits < min_bits) && (total_bits < n as u32 * gaggles as u32) {
                min_bits = total_bits;
                min_k = k;
            }
        }
        min_k
    } else {
        let mut delta: i64 = 0;
        let mut j = gaggles as i64;
        if start_index == 0 {
            j = gaggles as i64 - 1;
        }
        for i in start_index..(start_index + gaggles) {
            delta += mapped[i] as i64;
        }
        if HEUR_UNCODED_DELTA_MUL * delta >= HEUR_UNCODED_J_MUL * j * (1i64 << n) {
            UNCODED_FLAG
        } else if HEUR_K0_J_MUL * j > HEUR_K0_DELTA_MUL * delta {
            0
        } else if j * (1i64 << (n as i64 + HEUR_LARGE_K_SHIFT))
            <= HEUR_LARGE_K_DELTA_MUL * delta + HEUR_LARGE_K_J_MUL * j
        {
            n as i32 - 2
        } else {
            let mut min_k = 0;
            while j * (1i64 << (min_k as i64 + HEUR_SCAN_SHIFT_BASE))
                <= HEUR_SCAN_DELTA_MUL * delta + HEUR_SCAN_J_MUL * j
            {
                min_k += 1;
            }
            min_k - 1
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{select_rice_k, UNCODED_FLAG};
    use crate::types::GAGGLE_SIZE;

    #[test]
    fn exhaustive_search_picks_zero_for_small_values() {
        let mapped = vec![0u32; GAGGLE_SIZE];
        let k = select_rice_k(&mapped, 0, GAGGLE_SIZE, 8, 6, true);
        assert_eq!(k, 0);
    }

    #[test]
    fn exhaustive_search_falls_back_to_uncoded() {
        // Every value needs the full word width, so no k can beat uncoded output.
        let mapped = vec![0xFFu32; GAGGLE_SIZE];
        let k = select_rice_k(&mapped, 0, GAGGLE_SIZE, 8, 6, true);
        assert_eq!(k, UNCODED_FLAG);
    }

    #[test]
    fn exhaustive_search_stays_within_max_k() {
        let mapped: Vec<u32> = (0..GAGGLE_SIZE as u32).map(|i| i * 3).collect();
        let k = select_rice_k(&mapped, 0, GAGGLE_SIZE, 8, 6, true);
        assert!(
            k == UNCODED_FLAG || (0..=6).contains(&k),
            "unexpected k {}",
            k
        );
    }

    #[test]
    fn heuristic_picks_zero_for_small_values() {
        let mapped = vec![0u32; GAGGLE_SIZE];
        let k = select_rice_k(&mapped, 0, GAGGLE_SIZE, 8, 6, false);
        assert_eq!(k, 0);
    }

    #[test]
    fn heuristic_falls_back_to_uncoded() {
        let mapped = vec![0xFFu32; GAGGLE_SIZE];
        let k = select_rice_k(&mapped, 0, GAGGLE_SIZE, 8, 6, false);
        assert_eq!(k, UNCODED_FLAG);
    }

    /// Cross-checks against verify/vectors/rice_vectors.txt, generated by
    /// verify/c_unit_tests/gen_rice_vectors.c from the real C reference
    /// (linked against its actual ricecoding.o/bitsIO.o). Each line is
    /// `bit_length opt0 opt1 opt2 num_values bytes_hex`: encoding values
    /// 0..num_values with this module's rice_coding must produce the exact
    /// same bytes the C RiceCoding produced for the same sequence.
    ///
    /// Ignored by default (like golden_roundtrip.rs) because it needs
    /// verify/run_unit_vectors.py to have generated the vectors file first;
    /// that script runs this test with `--include-ignored`.

    #[test]
    fn heuristic_k_grows_with_magnitude() {
        let small: Vec<u32> = vec![4; GAGGLE_SIZE];
        let large: Vec<u32> = vec![40; GAGGLE_SIZE];
        let k_small = select_rice_k(&small, 0, GAGGLE_SIZE, 8, 6, false);
        let k_large = select_rice_k(&large, 0, GAGGLE_SIZE, 8, 6, false);
        assert!(
            k_large >= k_small,
            "k should not shrink as magnitudes grow: {} -> {}",
            k_small,
            k_large
        );
    }
}
